name: Deploy Docker-Advanced-App-Multi-Container
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t nirdeshkumar02/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true nirdeshkumar02/react-test npm test
 
      - run: docker build -t nirdeshkumar02/client -f ./client/Dockerfile.prod ./client
      - run: docker build -t nirdeshkumar02/nginx -f ./nginx/Dockerfile.prod ./nginx
      - run: docker build -t nirdeshkumar02/server -f ./server/Dockerfile.prod ./server
      - run: docker build -t nirdeshkumar02/worker -f ./worker/Dockerfile.prod ./worker
 
      - run: docker push nirdeshkumar02/client
      - run: docker push nirdeshkumar02/nginx
      - run: docker push nirdeshkumar02/server
      - run: docker push nirdeshkumar02/worker
 
      # - name: Generate deployment package
      #   run: zip -r deploy.zip . -x '*.git*'
 
      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v18
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: docker-app-multi-container
      #     environment_name: Multigh-env
      #     existing_bucket_name: elasticbeanstalk-us-east-1-626170306581
      #     region: us-east-1
      #     version_label: ${{ github.sha }}
      #     deployment_package: deploy.zip